### ISSUE TITLE
can't download when you add annotation [dyAnnotation]

### ISSUE THREAD

**Issue by brunelserge** [joh024/dygraph-extra#2]
hello

when i add annotation to the `dygraph`with `dyAnnotation`download doesnt work
i just add one annotation to your example :

```
library(shiny)
library(dygraphs)
source("dygraph-extra-shiny.R")

shinyServer(function(input, output, session){
  ## Using one of the demos from https://rstudio.github.io/dygraphs/
  ## Only addition is the line adding the callback
  ##  to register the dygraph with dygraph-extra
  hw <- HoltWinters(ldeaths)
  predicted <- predict(hw, n.ahead = 72, prediction.interval = TRUE)

  outdy = dygraph(predicted, main = "Predicted Lung Deaths (UK)") %>%
    dyAxis("x", drawGrid = FALSE) %>%
   dySeries(c("lwr", "fit", "upr"), label = "Deaths") %>%
    dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>% 
    dyAnnotation(as.POSIXlt("1985-02-14") ,
                 text = paste("birthday"),
                 attachAtBottom = F,
                 width = 60,
                 height = 25)%>%
    dyCallbacks(drawCallback = dyRegister())

     output$dyout = renderDygraph(outdy)
    })
```

the script run no R error or warning but there is a javascript error :
TypeError: Dygraph.Export.putLabelAnn is not a function

thank you

**Comment by joh024** [comment]
Hmm, that's interesting, the original `dygraph-extra` code refers to a `Dygraph.Export.putLabelAnn` function for drawing annotations, but it seems they never wrote one.

I'll see if I can write one to do that. For now, I guess you can't use annotations.

**Comment by joh024** [comment]
I've added basic support for annotations.
Only the annotation itself is drawn, the tooltip is ignored (for now? Maybe I'll get around to having it printed out bottom like the legends).

![predicted lung deaths uk](https://cloud.githubusercontent.com/assets/3042623/19374926/14a42d8c-922c-11e6-915b-e85fe69b9f30.png)

It should look the same if the text in the annotation fits in the box. If it doesn't, then the actual dygraph will have text clipped and hidden, while the exported image will have text overflowing out (this is due to differences in how HTML and Canvas draw text).

**Comment by brunelserge** [comment]
thank you the download is working now but there is a problem in annotation position 
- top the signal is on the peak that's my application
- bot the signal are moved to the right when downloaded 

![bug_dl_dygraph](https://cloud.githubusercontent.com/assets/5072903/19379570/fe7f777a-91f2-11e6-922f-1fb6142f899d.PNG)

**Comment by joh024** [comment]
The positions are grabbed from the `div` positions, so they should match up (and the annotation are in the same places relative to the title position, so that seems to be working correctly), but for some reason it seems your actual graph has shifted (the left peak has moved to the "he" in "ther", when it peaked below where the annotation was).

Is anything causing a change in widths as the download happens?

Are you able to provide that shiny app, or another one where you face the same issue, so I can test it myself?

**Comment by brunelserge** [comment]
i can't share my app but here is a test example
i tried without `shinydashboard`same problem 

test 
-  it's working on `chrome` (good position )
- `firefox` download works but bad position
-  `ie 11.0.9600`   not working at all

ui

```
 library(shiny)
 library(dygraphs)
 source("dygraph-extra-shiny.R")

 shinyUI(fluidPage(
   tags$head(
     tags$script(src = "dygraph-extra.js")
   ),
   titlePanel("dygraph-extra shiny-example"),
   div(style = "width: 100%;",
     dyDownload("dyout", "Download Plot", asbutton = TRUE),
     dygraphOutput("dyout", height = 600)
        )       
      ))
```

server

```
      library(shiny)
      library(dygraphs)
      source("dygraph-extra-shiny.R")

      shinyServer(function(input, output, session){
        ## Using one of the demos from https://rstudio.github.io/dygraphs/
        ## Only addition is the line adding the callback
        ##  to register the dygraph with dygraph-extra

        x.Date <- as.Date("2003-02-01") + c(1, 3, 7, 9, 14) - 1
        x <- zoo(rnorm(5), x.Date)

        outdy = dygraph(x, main = "sample xts") %>%
          dyAxis("x", drawGrid = FALSE) %>%
          dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1")) %>% 
           dyAnnotation( time(x)[3] ,
                         text = paste("signal"),
               tooltip =  "low",
               attachAtBottom = F,
               width = 60,
               height = 25) %>%
          dyCallbacks(drawCallback = dyRegister())

        output$dyout = renderDygraph(outdy)
      })
```

**Comment by joh024** [comment]
Hmm, using Firefox 49.0.1 I get the correct result as below:

![sample xts](https://cloud.githubusercontent.com/assets/3042623/19382118/3ec386ce-925b-11e6-815c-db0d8f85dd5b.png)

It's #1 all over again! Weird alignment issues that I can't reproduce on my end.

**Comment by brunelserge** [comment]
when i run it from Rstudio (my desktop) only chrome works
when i run on the real shiny server only firefox works

thanks

chrome error :
Uncaught TypeError: Object.values is not a functionDygraph.Export.drawAnnotes @ dygraph-extra.js:446Dygraph.Export.drawPlot @ dygraph-extra.js:265Dygraph.Export.asCanvas @ dygraph-extra.js:204getPNG @ dygraph-extra.js:506Dygraph.Export.DownloadByID @ dygraph-extra.js:515onclick @ (index):134

**Comment by joh024** [comment]
My bad, `Object.values` is Firefox only experimental API. I've changed the code so it doesn't use it anymore.

Ah, I wonder if RStudio is doing something fishy. I don't use it (or even have it installed).

**Comment by brunelserge** [comment]
it's working on chrome, firefox and Rstudio now ! [closed]
thank you

**Comment by joh024** [comment]
Great.
