### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by mmaukii** [joh024/dygraph-extra#5]
Hello!

Thank you for the great tool. I would have one question. I use shiny locally and would need this function to save dygraphs on my hard disk. Everytime on the same place with the same name (so the downlaod path selection dialogue would not be neede). I tried to find out, where i could change the code to do so (more are less pass a fixed path from shiny to the javascript or so) but i got lost totally. I have never worked with javascript so maybe you can give me a hint?

Greets and thanks ikua

**Comment by joh024** [comment]
To my knowledge, for security reasons, JavaScript cannot write to or read from local files directly except through some restricted methods, in this case going through the browser's download file dialogue.

You might be able to achieve your desired result by setting up your browser to automatically download to a certain path, but as far as I know, your issue isn't something that can be handled via JavaScript.

**Comment by mmaukii** [comment]
Thank you for the answert
